# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171107_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mota',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
