# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171107_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mota',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
