# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171107_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='mota',
            new_name='hinhanh',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='hanhtrinh',
            new_name='noidung',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='songay',
        ),
        migrations.AddField(
            model_name='blog',
            name='gia',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
