# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gia',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
