# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_ngaydi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id', '-ngaydang']},
        ),
    ]
