# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloai', models.TextField(max_length=200)),
                ('nguongoc', models.TextField()),
                ('img_nguongoc', models.ImageField(blank=True, null=True, upload_to='')),
                ('tinhcam', models.TextField()),
                ('img_tinhcam', models.ImageField(blank=True, null=True, upload_to='')),
                ('tinhcach', models.TextField()),
                ('img_tinhcach', models.ImageField(blank=True, null=True, upload_to='')),
                ('ngaydang', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
