# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ngaydang',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
