# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171206_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ngaydang',
            field=models.DateTimeField(),
        ),
    ]
