# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_remove_blog_ngaydi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('diachi', models.CharField(max_length=250)),
                ('dienthoai', models.CharField(max_length=20)),
                ('thanhpho', models.CharField(max_length=100)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaycapnhat', models.DateTimeField(auto_now=True)),
                ('thanhtoan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=100)),
                ('soluong', models.PositiveIntegerField(default=1)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='blog.Blog')),
            ],
        ),
    ]
