# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hinhthucthanhtoan',
            field=models.CharField(default='Thanh toán otp', max_length=150),
            preserve_default=False,
        ),
    ]
